<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIST [
<!-- 2006/02/11 -->
<!ELEMENT LIST (ITEM*)><!-- primitive list -->
<!ELEMENT ITEM (NAME?, DESC?)><!-- primitive item -->
<!ELEMENT NAME (#PCDATA)><!-- primitive item -->
<!ELEMENT TIP (#PCDATA)><!-- primitive item -->
<!ELEMENT DESC (#PCDATA)><!-- primitive item -->
<!ATTLIST ITEM KEY CDATA #REQUIRED>
<!ATTLIST LIST KEY CDATA #IMPLIED>
]>

<LIST>
    <ITEM KEY="LaTeX_Document_Macro">
        <NAME>LaTeX Document Macro</NAME>
    </ITEM>
    <ITEM KEY="part">
        <NAME>part</NAME>
    </ITEM>
    <ITEM KEY="chapter">
        <NAME>chapter</NAME>
    </ITEM>
    <ITEM KEY="section">
        <NAME>section</NAME>
    </ITEM>
    <ITEM KEY="subsection">
        <NAME>subsection</NAME>
    </ITEM>
    <ITEM KEY="subsubsection">
        <NAME>subsubsection</NAME>
    </ITEM>
    <ITEM KEY="paragraph">
        <NAME>paragraph</NAME>
    </ITEM>
    <ITEM KEY="subparagraph">
        <NAME>subparagraph</NAME>
    </ITEM>
    <ITEM KEY="document">
        <NAME>document</NAME>
    </ITEM>
    <ITEM KEY="document/book">
        <NAME>book</NAME>
    </ITEM>
    <ITEM KEY="document/book/10pt">
        <NAME>10pt</NAME>
    </ITEM>
    <ITEM KEY="document/book/11pt">
        <NAME>11pt</NAME>
    </ITEM>
    <ITEM KEY="document/book/12pt">
        <NAME>12pt</NAME>
    </ITEM>
    <ITEM KEY="document/amsbook">
        <NAME>amsbook</NAME>
    </ITEM>
    <ITEM KEY="document/amsbook/10pt">
        <NAME>10pt</NAME>
    </ITEM>
    <ITEM KEY="document/amsbook/11pt">
        <NAME>11pt</NAME>
    </ITEM>
    <ITEM KEY="document/amsbook/12pt">
        <NAME>12pt</NAME>
    </ITEM>
    <ITEM KEY="document/report">
        <NAME>report</NAME>
    </ITEM>
    <ITEM KEY="document/report/10pt">
        <NAME>10pt</NAME>
    </ITEM>
    <ITEM KEY="document/report/11pt">
        <NAME>11pt</NAME>
    </ITEM>
    <ITEM KEY="document/report/12pt">
        <NAME>12pt</NAME>
    </ITEM>
    <ITEM KEY="document/article">
        <NAME>article</NAME>
    </ITEM>
    <ITEM KEY="document/article/10pt">
        <NAME>10pt</NAME>
    </ITEM>
    <ITEM KEY="document/article/11pt">
        <NAME>11pt</NAME>
    </ITEM>
    <ITEM KEY="document/article/12pt">
        <NAME>12pt</NAME>
    </ITEM>
    <ITEM KEY="document/amsart">
        <NAME>amsart</NAME>
    </ITEM>
    <ITEM KEY="document/amsart/10pt">
        <NAME>10pt</NAME>
    </ITEM>
    <ITEM KEY="document/amsart/11pt">
        <NAME>11pt</NAME>
    </ITEM>
    <ITEM KEY="document/amsart/12pt">
        <NAME>12pt</NAME>
    </ITEM>
    <ITEM KEY="document/letter">
        <NAME>letter</NAME>
    </ITEM>
    <ITEM KEY="document/letter/10pt">
        <NAME>10pt</NAME>
    </ITEM>
    <ITEM KEY="document/letter/11pt">
        <NAME>11pt</NAME>
    </ITEM>
    <ITEM KEY="document/letter/12pt">
        <NAME>12pt</NAME>
    </ITEM>
    <ITEM KEY="document/letter/macros">
        <NAME>macros</NAME>
    </ITEM>
    <ITEM KEY="document/letter/macros/begin/end_doc/letter">
        <NAME>begin/end doc/letter</NAME>
    </ITEM>
    <ITEM KEY="document/letter/macros/name">
        <NAME>name</NAME>
    </ITEM>
    <ITEM KEY="document/letter/macros/address">
        <NAME>address</NAME>
    </ITEM>
    <ITEM KEY="document/letter/macros/signature">
        <NAME>signature</NAME>
    </ITEM>
    <ITEM KEY="document/letter/macros/date">
        <NAME>date</NAME>
    </ITEM>
    <ITEM KEY="document/letter/macros/opening">
        <NAME>opening</NAME>
    </ITEM>
    <ITEM KEY="document/letter/macros/closing">
        <NAME>closing</NAME>
    </ITEM>
    <ITEM KEY="document/letter/macros/encl">
        <NAME>encl</NAME>
    </ITEM>
    <ITEM KEY="document/letter/macros/cc">
        <NAME>cc</NAME>
    </ITEM>
    <ITEM KEY="document/Options">
        <NAME>Options</NAME>
    </ITEM>
    <ITEM KEY="document/Options/landscape">
        <NAME>landscape</NAME>
    </ITEM>
    <ITEM KEY="document/Options/draft">
        <NAME>draft</NAME>
    </ITEM>
    <ITEM KEY="document/Options/openbib">
        <NAME>openbib</NAME>
    </ITEM>
    <ITEM KEY="document/Options/paper">
        <NAME>paper</NAME>
    </ITEM>
    <ITEM KEY="document/Options/paper/letter_paper">
        <NAME>letter paper</NAME>
    </ITEM>
    <ITEM KEY="document/Options/paper/legal_paper">
        <NAME>legal paper</NAME>
    </ITEM>
    <ITEM KEY="document/Options/paper/executive_paper">
        <NAME>executive paper</NAME>
    </ITEM>
    <ITEM KEY="document/Options/paper/a4_paper">
        <NAME>a4 paper</NAME>
    </ITEM>
    <ITEM KEY="document/Options/paper/a5_paper">
        <NAME>a5 paper</NAME>
    </ITEM>
    <ITEM KEY="document/Options/paper/B5_paper">
        <NAME>B5 paper</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions">
        <NAME>Dimensions</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/pageheight">
        <NAME>pageheight</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/topmargin">
        <NAME>topmargin</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/headheight">
        <NAME>headheight</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/headsep">
        <NAME>headsep</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/textheight">
        <NAME>textheight</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/footskip">
        <NAME>footskip</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/pagewidth">
        <NAME>pagewidth</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/oddsidemargin">
        <NAME>oddsidemargin</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/evensidemargin">
        <NAME>evensidemargin</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/textwidth">
        <NAME>textwidth</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/marginparsep">
        <NAME>marginparsep</NAME>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/marginparwidth">
        <NAME>marginparwidth</NAME>
    </ITEM>
    <ITEM KEY="document/Options/sides">
        <NAME>sides</NAME>
    </ITEM>
    <ITEM KEY="document/Options/sides/one_side">
        <NAME>one side</NAME>
    </ITEM>
    <ITEM KEY="document/Options/sides/two_sides">
        <NAME>two sides</NAME>
    </ITEM>
    <ITEM KEY="document/Options/columns">
        <NAME>columns</NAME>
    </ITEM>
    <ITEM KEY="document/Options/columns/one_column">
        <NAME>one column</NAME>
    </ITEM>
    <ITEM KEY="document/Options/columns/two_columns">
        <NAME>two columns</NAME>
    </ITEM>
    <ITEM KEY="document/Options/title">
        <NAME>title</NAME>
    </ITEM>
    <ITEM KEY="document/Options/title/no_title_page">
        <NAME>no title page</NAME>
    </ITEM>
    <ITEM KEY="document/Options/title/title_page">
        <NAME>title page</NAME>
    </ITEM>
    <ITEM KEY="document/Options/equation">
        <NAME>equation</NAME>
    </ITEM>
    <ITEM KEY="document/Options/equation/left">
        <NAME>left</NAME>
    </ITEM>
    <ITEM KEY="document/Options/equation/left_align">
        <NAME>left align</NAME>
    </ITEM>
    <ITEM KEY="Format">
        <NAME>Format</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph">
        <NAME>paragraph</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph/indent">
        <NAME>indent</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph/noindent">
        <NAME>noindent</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph/par">
        <NAME>par</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters">
        <NAME>parameters</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/textwidth">
        <NAME>textwidth</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/linewidth">
        <NAME>linewidth</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/parindent">
        <NAME>parindent</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/baselineskip">
        <NAME>baselineskip</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/baselinestretch">
        <NAME>baselinestretch</NAME>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/parskip">
        <NAME>parskip</NAME>
    </ITEM>
    <ITEM KEY="Format/marginal_notes">
        <NAME>marginal notes</NAME>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/marginpar">
        <NAME>marginpar</NAME>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/normalmarginpar">
        <NAME>normalmarginpar</NAME>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/reversemarginpar">
        <NAME>reversemarginpar</NAME>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/parameters">
        <NAME>parameters</NAME>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/parameters/marginparwidth">
        <NAME>marginparwidth</NAME>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/parameters/marginparsep">
        <NAME>marginparsep</NAME>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/parameters/marginparpush">
        <NAME>marginparpush</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering">
        <NAME>numbering</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/newcounter">
        <NAME>newcounter</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/setcounter">
        <NAME>setcounter</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/addtocounter">
        <NAME>addtocounter</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/value">
        <NAME>value</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/the">
        <NAME>the</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/style">
        <NAME>style</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/style/arabic">
        <NAME>arabic</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/style/roman">
        <NAME>roman</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/style/Roman">
        <NAME>Roman</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/style/alph">
        <NAME>alph</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/style/Alph">
        <NAME>Alph</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/fnsymbol">
        <NAME>fnsymbol</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/stepcounter">
        <NAME>stepcounter</NAME>
    </ITEM>
    <ITEM KEY="Format/numbering/refstepcounter">
        <NAME>refstepcounter</NAME>
    </ITEM>
    <ITEM KEY="Format/footnote">
        <NAME>footnote</NAME>
    </ITEM>
    <ITEM KEY="Format/footnote/footnote">
        <NAME>footnote</NAME>
    </ITEM>
    <ITEM KEY="Format/footnote/footnotemark">
        <NAME>footnotemark</NAME>
    </ITEM>
    <ITEM KEY="Format/footnote/footnotetext">
        <NAME>footnotetext</NAME>
    </ITEM>
    <ITEM KEY="Format/footnote/parameters">
        <NAME>parameters</NAME>
    </ITEM>
    <ITEM KEY="Format/footnote/parameters/footnotesep">
        <NAME>footnotesep</NAME>
    </ITEM>
    <ITEM KEY="Format/footnote/parameters/footnoterule">
        <NAME>footnoterule</NAME>
    </ITEM>
    <ITEM KEY="Format/footnote/caption">
        <NAME>caption</NAME>
    </ITEM>
    <ITEM KEY="Format/footnote/vspace">
        <NAME>vspace</NAME>
    </ITEM>
    <ITEM KEY="Page_Style">
        <NAME>Page Style</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/title_page">
        <NAME>title page</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_style">
        <NAME>page style</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_style/plain">
        <NAME>plain</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_style/empty">
        <NAME>empty</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_style/headings">
        <NAME>headings</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_style/myheadings">
        <NAME>myheadings</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style">
        <NAME>this page style</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/plain">
        <NAME>plain</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/empty">
        <NAME>empty</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/headings">
        <NAME>headings</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/myheadings">
        <NAME>myheadings</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/Left_heading">
        <NAME>Left heading</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/Right_heading">
        <NAME>Right heading</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/Both_headings">
        <NAME>Both headings</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering">
        <NAME>page numbering</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering/arabic">
        <NAME>arabic</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering/roman">
        <NAME>roman</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering/Roman">
        <NAME>Roman</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering/alph">
        <NAME>alph</NAME>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering/Alph">
        <NAME>Alph</NAME>
    </ITEM>
    <ITEM KEY="Layout">
        <NAME>Layout</NAME>
    </ITEM>
    <ITEM KEY="Layout/landscape">
        <NAME>landscape</NAME>
    </ITEM>
    <ITEM KEY="Layout/Use_lscape_Pkg">
        <NAME>Use lscape Pkg</NAME>
    </ITEM>
    <ITEM KEY="%!iTeXMac">
        <NAME>%!iTeXMac</NAME>
    </ITEM>
    <ITEM KEY="%!iTeXMac/project">
        <NAME>project</NAME>
    </ITEM>
    <ITEM KEY="%!iTeXMac/input">
        <NAME>input</NAME>
    </ITEM>
    <ITEM KEY="%!iTeXMac/compile">
        <NAME>compile</NAME>
    </ITEM>
    <ITEM KEY="%!iTeXMac/typeset">
        <NAME>typeset</NAME>
    </ITEM>
    <ITEM KEY="%!iTeXMac/bibtex">
        <NAME>bibtex</NAME>
    </ITEM>
    <ITEM KEY="%!iTeXMac/makeindex">
        <NAME>makeindex</NAME>
    </ITEM>
</LIST>