<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIST [
<!-- 2006/02/11 -->
<!ELEMENT ITEM (ARG?)><!-- primitive item -->
<!ELEMENT ARG (#PCDATA)><!-- argument -->
<!ELEMENT LIST (ITEM*)><!-- primitive list -->
<!ATTLIST ITEM KEY CDATA #REQUIRED>
<!ATTLIST LIST KEY CDATA #IMPLIED>
]>

<LIST>
    <ITEM KEY="part">
        <ARG>\part{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="chapter">
        <ARG>\chapter{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="section">
        <ARG>\section{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="subsection">
        <ARG>\subsection{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="subsubsection">
        <ARG>\subsubsection{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="paragraph">
        <ARG>\paragraph{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="subparagraph">
        <ARG>\subparagraph{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="document/book/10pt">
        <ARG>\documentclass{book}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/book/11pt">
        <ARG>\documentclass[11pt]{book}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/book/12pt">
        <ARG>\documentclass[12pt]{book}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/amsbook/10pt">
        <ARG>\documentclass{amsbook}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/amsbook/11pt">
        <ARG>\documentclass[11pt]{amsbook}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/amsbook/12pt">
        <ARG>\documentclass[12pt]{amsbook}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/report/10pt">
        <ARG>\documentclass{report}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/report/11pt">
        <ARG>\documentclass[11pt]{report}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/report/12pt">
        <ARG>\documentclass[12pt]{report}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/article/10pt">
        <ARG>\documentclass{article}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/article/11pt">
        <ARG>\documentclass[11pt]{article}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/article/12pt">
        <ARG>\documentclass[12pt]{article}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/amsart/10pt">
        <ARG>\documentclass{amsart}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/amsart/11pt">
        <ARG>\documentclass[11pt]{amsart}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/amsart/12pt">
        <ARG>\documentclass[12pt]{amsart}
\begin{document}
__(INS)__

\end{document}
</ARG>
    </ITEM>
    <ITEM KEY="document/letter/10pt">
        <ARG>\documentclass{letter}
</ARG>
    </ITEM>
    <ITEM KEY="document/letter/11pt">
        <ARG>\documentclass[11pt]{letter}
</ARG>
    </ITEM>
    <ITEM KEY="document/letter/12pt">
        <ARG>\documentclass[12pt]{letter}
</ARG>
    </ITEM>
    <ITEM KEY="document/letter/macros/begin/end_doc/letter">
        <ARG>\begin{document}
\begin{letter}
__(INS)__

\end{letter}
\end{document}</ARG>
    </ITEM>
    <ITEM KEY="document/letter/macros/name">
        <ARG>\name{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="document/letter/macros/address">
        <ARG>\address{__(INS)____(SEL)____(INS)__}
 </ARG>
    </ITEM>
    <ITEM KEY="document/letter/macros/signature">
        <ARG>\signature{__(INS)____(SEL)____(INS)__}
 </ARG>
    </ITEM>
    <ITEM KEY="document/letter/macros/date">
        <ARG>\date{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="document/letter/macros/opening">
        <ARG>\opening{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="document/letter/macros/closing">
        <ARG>\closing{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="document/letter/macros/encl">
        <ARG>\encl{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="document/letter/macros/cc">
        <ARG>\cc{__(INS)____(SEL)____(INS)__}
</ARG>
    </ITEM>
    <ITEM KEY="document/Options/landscape">
        <ARG>landscape</ARG>
    </ITEM>
    <ITEM KEY="document/Options/draft">
        <ARG>draft</ARG>
    </ITEM>
    <ITEM KEY="document/Options/openbib">
        <ARG>openbib</ARG>
    </ITEM>
    <ITEM KEY="document/Options/paper/letter_paper">
        <ARG>letterpaper</ARG>
    </ITEM>
    <ITEM KEY="document/Options/paper/legal_paper">
        <ARG>legalpaper</ARG>
    </ITEM>
    <ITEM KEY="document/Options/paper/executive_paper">
        <ARG>executivepaper</ARG>
    </ITEM>
    <ITEM KEY="document/Options/paper/a4_paper">
        <ARG>a4paper</ARG>
    </ITEM>
    <ITEM KEY="document/Options/paper/a5_paper">
        <ARG>a5paper</ARG>
    </ITEM>
    <ITEM KEY="document/Options/paper/B5_paper">
        <ARG>b5paper</ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/pageheight">
        <ARG>\pageheight </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/topmargin">
        <ARG>\topmargin </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/headheight">
        <ARG>\headheight </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/headsep">
        <ARG>\headsep </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/textheight">
        <ARG>\textheight </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/footskip">
        <ARG>\footskip </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/pagewidth">
        <ARG>\pagewidth </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/oddsidemargin">
        <ARG>\oddsidemargin </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/evensidemargin">
        <ARG>\evensidemargin </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/textwidth">
        <ARG>\textwidth </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/marginparsep">
        <ARG>\marginparsep </ARG>
    </ITEM>
    <ITEM KEY="document/Options/Dimensions/marginparwidth">
        <ARG>\marginparwidth </ARG>
    </ITEM>
    <ITEM KEY="document/Options/sides/one_side">
        <ARG>oneside</ARG>
    </ITEM>
    <ITEM KEY="document/Options/sides/two_sides">
        <ARG>twoside</ARG>
    </ITEM>
    <ITEM KEY="document/Options/columns/one_column">
        <ARG>onecolumn</ARG>
    </ITEM>
    <ITEM KEY="document/Options/columns/two_columns">
        <ARG>twocolumn</ARG>
    </ITEM>
    <ITEM KEY="document/Options/title/no_title_page">
        <ARG>notitlepage</ARG>
    </ITEM>
    <ITEM KEY="document/Options/title/title_page">
        <ARG>titlepage</ARG>
    </ITEM>
    <ITEM KEY="document/Options/equation/left">
        <ARG>leqno</ARG>
    </ITEM>
    <ITEM KEY="document/Options/equation/left_align">
        <ARG>fleqn</ARG>
    </ITEM>
    <ITEM KEY="Format/paragraph/indent">
        <ARG>\indent </ARG>
    </ITEM>
    <ITEM KEY="Format/paragraph/noindent">
        <ARG>\noindent </ARG>
    </ITEM>
    <ITEM KEY="Format/paragraph/par">
        <ARG>\par </ARG>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/textwidth">
        <ARG>\textwidth </ARG>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/linewidth">
        <ARG>\linewidth </ARG>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/parindent">
        <ARG>\parindent </ARG>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/baselineskip">
        <ARG>\baselineskip </ARG>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/baselinestretch">
        <ARG>\baselinestretch </ARG>
    </ITEM>
    <ITEM KEY="Format/paragraph/parameters/parskip">
        <ARG>\parskip </ARG>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/marginpar">
        <ARG>\marginpar[__(INS)____(SEL)____(INS)__]{}</ARG>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/normalmarginpar">
        <ARG>\normalmarginpar</ARG>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/reversemarginpar">
        <ARG>\reversemarginpar</ARG>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/parameters/marginparwidth">
        <ARG>\marginparwidth </ARG>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/parameters/marginparsep">
        <ARG>\marginparsep </ARG>
    </ITEM>
    <ITEM KEY="Format/marginal_notes/parameters/marginparpush">
        <ARG>\marginparpush </ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/newcounter">
        <ARG>\newcounter{__(INS)____(SEL)____(INS)__}[]</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/setcounter">
        <ARG>\setcounter{__(INS)____(SEL)____(INS)__}{}</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/addtocounter">
        <ARG>\addtocounter{__(INS)____(SEL)____(INS)__}{}</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/value">
        <ARG>\value{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/the">
        <ARG>\the__(INS)__</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/style/arabic">
        <ARG>\arabic{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/style/roman">
        <ARG>\roman{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/style/Roman">
        <ARG>\Roman{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/style/alph">
        <ARG>\alph{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/style/Alph">
        <ARG>\Alph{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/fnsymbol">
        <ARG>\fnsymbol{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/stepcounter">
        <ARG>\stepcounter{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Format/numbering/refstepcounter">
        <ARG>\refstepcounter{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Format/footnote/footnote">
        <ARG>\footnote[__(INS)____(SEL)____(INS)__]{}</ARG>
    </ITEM>
    <ITEM KEY="Format/footnote/footnotemark">
        <ARG>\footnotemark[__(INS)____(SEL)____(INS)__]</ARG>
    </ITEM>
    <ITEM KEY="Format/footnote/footnotetext">
        <ARG>\footnotetext[__(INS)____(SEL)____(INS)__]{}</ARG>
    </ITEM>
    <ITEM KEY="Format/footnote/parameters/footnotesep">
        <ARG>\footnotesep </ARG>
    </ITEM>
    <ITEM KEY="Format/footnote/parameters/footnoterule">
        <ARG>\footnoterule </ARG>
    </ITEM>
    <ITEM KEY="Format/footnote/caption">
        <ARG>\caption</ARG>
    </ITEM>
    <ITEM KEY="Format/footnote/vspace">
        <ARG>\vspace</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/title_page">
        <ARG>\title{__(INS)__TITLE HERE__(INS)__}
\author{AUTHOR NAME HERE}
\date{DATE HERE}
\maketitle

</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/page_style/plain">
        <ARG>\pagestyle{plain}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/page_style/empty">
        <ARG>\pagestyle{empty}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/page_style/headings">
        <ARG>\pagestyle{headings}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/page_style/myheadings">
        <ARG>\pagestyle{myheadings}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/plain">
        <ARG>\thispagestyle{plain}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/empty">
        <ARG>\thispagestyle{empty}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/headings">
        <ARG>\thispagestyle{headings}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/myheadings">
        <ARG>\thispagestyle{myheadings}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/Left_heading">
        <ARG>\markleft{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/Right_heading">
        <ARG>\markright{__(INS)____(SEL)____(INS)__}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/this_page_style/Both_headings">
        <ARG>\markboth{__(INS)____(SEL)____(INS)__}{RIGHT HERE}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering/arabic">
        <ARG>\pagenumbering{arabic}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering/roman">
        <ARG>\pagenumbering{roman}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering/Roman">
        <ARG>\pagenumbering{Roman}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering/alph">
        <ARG>\pagenumbering{alph}</ARG>
    </ITEM>
    <ITEM KEY="Page_Style/page_numbering/Alph">
        <ARG>\pagenumbering{Alph}</ARG>
    </ITEM>
    <ITEM KEY="Layout/landscape">
        <ARG>\begin{landscape}
__(SEL)__
\end{landscape}</ARG>
    </ITEM>
    <ITEM KEY="Layout/Use_lscape_Pkg">
        <ARG>\usepackage{lscape}
</ARG>
    </ITEM>
    <ITEM KEY="%!iTeXMac/project" ACT="insertDirective:">
        <ARG>%!iTeXMac(project): __(INS)__</ARG>
    </ITEM>
    <ITEM KEY="%!iTeXMac/input" ACT="insertDirective:">
        <ARG>%!iTeXMac(input): __(INS)__</ARG>
    </ITEM>
    <ITEM KEY="%!iTeXMac/compile" ACT="insertDirective:">
        <ARG>%!iTeXMac(compile): __(INS)__</ARG>
    </ITEM>
    <ITEM KEY="%!iTeXMac/typeset" ACT="insertDirective:">
        <ARG>%!iTeXMac(typeset): __(INS)__</ARG>
    </ITEM>
    <ITEM KEY="%!iTeXMac/bibtex" ACT="insertDirective:">
        <ARG>%!iTeXMac(bibtex): __(INS)__</ARG>
    </ITEM>
    <ITEM KEY="%!iTeXMac/makeindex" ACT="insertDirective:">
        <ARG>%!iTeXMac(makeindex): __(INS)__</ARG>
    </ITEM>
</LIST>