<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MAIN[
<!ELEMENT MAIN (
WINDOW_TITLE,
MAIN_INDEX,
BOOK_TITLE,
TOPIC_LIST,
NEWBIE,
NEWBIE_TOPIC,
TOP_QUESTION_LIST,
WEB_LIST
)>
<!ATTLIST MAIN COPYRIGHT CDATA "Copyright 2006 Laurens'Tribune for iTeXMac2.">
<!ATTLIST MAIN STYLESHEET CDATA "sty/iapp_styleh.css">
<!ATTLIST MAIN KEYWORDS CDATA #IMPLIED>
<!ATTLIST MAIN DESCRIPTION CDATA #IMPLIED>
<!ATTLIST MAIN AppleTitle CDATA #REQUIRED>
<!ATTLIST MAIN AppleIcon CDATA #REQUIRED>
<!ATTLIST MAIN ANCHOR CDATA "iTM2001">
<!ELEMENT WINDOW_TITLE (#PCDATA)>
<!ELEMENT MAIN_HELP (#PCDATA)>
<!ATTLIST MAIN_HELP HREF CDATA #IMPLIED>
<!ELEMENT MAIN_INDEX (#PCDATA)>
<!ATTLIST MAIN_INDEX HREF CDATA #IMPLIED>
<!ELEMENT BOOK_TITLE (#PCDATA)>
<!ATTLIST BOOK_TITLE IMG CDATA "gfx/iTeXMac2.png">
<!ELEMENT TOPIC_LIST (TOPIC_LIST_TITLE,(TOPIC)+)>
<!ELEMENT TOPIC_LIST_TITLE (#PCDATA)>
<!ELEMENT TOPIC (TOPIC_TITLE,TOPIC_DESCRIPTION)>
<!ATTLIST TOPIC HREF CDATA #REQUIRED>
<!ATTLIST TOPIC IMG CDATA #REQUIRED>
<!ELEMENT TOPIC_TITLE (#PCDATA)>
<!ELEMENT TOPIC_DESCRIPTION (#PCDATA)>
<!ELEMENT NEWBIE (#PCDATA)>
<!ELEMENT NEWBIE_TOPIC (NEWBIE_TOPIC_TITLE,NEWBIE_TOPIC_DESCRIPTION)>
<!ATTLIST NEWBIE_TOPIC HREF CDATA #REQUIRED>
<!ELEMENT NEWBIE_TOPIC_TITLE (#PCDATA)>
<!ELEMENT NEWBIE_TOPIC_DESCRIPTION (#PCDATA)>
<!ELEMENT TOP_QUESTION_LIST (TOP_QUESTION_TITLE, (TOP_QUESTION)*)>
<!ELEMENT TOP_QUESTION_TITLE (#PCDATA)>
<!ELEMENT TOP_QUESTION (#PCDATA)>
<!ATTLIST TOP_QUESTION HREF CDATA #IMPLIED>
<!ELEMENT WEB_LIST (WEB_LIST_TITLE,(WEB)+)>
<!ELEMENT WEB_LIST_TITLE (#PCDATA)>
<!ELEMENT WEB (WEB_TITLE,WEB_DESCRIPTION)>
<!ATTLIST WEB HREF CDATA #REQUIRED>
<!ELEMENT WEB_TITLE (#PCDATA)>
<!ELEMENT WEB_DESCRIPTION (#PCDATA)>
]>
<MAIN AppleTitle="iTeXMac2" AppleIcon="gfx/iTeXMac2.png" >
    <WINDOW_TITLE>Window title</WINDOW_TITLE>
    <MAIN_INDEX HREF="index reference">Main Index</MAIN_INDEX>
    <BOOK_TITLE>Main title</BOOK_TITLE>
    <TOPIC_LIST>
        <TOPIC_LIST_TITLE>Topic list title</TOPIC_LIST_TITLE>
        <TOPIC HREF="reference" IMG="gfx/my image">
            <TOPIC_TITLE>titre de topic</TOPIC_TITLE>
            <TOPIC_DESCRIPTION>description de topic</TOPIC_DESCRIPTION>
        </TOPIC>
        <TOPIC HREF="reference1" IMG="gfx/my image1">
            <TOPIC_TITLE>titre de topic1</TOPIC_TITLE>
            <TOPIC_DESCRIPTION>description de topic1</TOPIC_DESCRIPTION>
        </TOPIC>
    </TOPIC_LIST>
    <NEWBIE>Nouveau?</NEWBIE>
    <NEWBIE_TOPIC HREF="reference">
        <NEWBIE_TOPIC_TITLE>titre de topic 00</NEWBIE_TOPIC_TITLE>
        <NEWBIE_TOPIC_DESCRIPTION>description de topic</NEWBIE_TOPIC_DESCRIPTION>
    </NEWBIE_TOPIC>
    <TOP_QUESTION_LIST>
        <TOP_QUESTION_TITLE>Questions top</TOP_QUESTION_TITLE>
        <TOP_QUESTION HREF="reference">
            top question
        </TOP_QUESTION>
    </TOP_QUESTION_LIST>
    <WEB_LIST>
        <WEB_LIST_TITLE>2nd titre</WEB_LIST_TITLE>
        <WEB HREF="reference">
            <WEB_TITLE>titre de topic</WEB_TITLE>
            <WEB_DESCRIPTION>description de topic</WEB_DESCRIPTION>
        </WEB>
        <WEB HREF="reference1">
            <WEB_TITLE>titre de topic1</WEB_TITLE>
            <WEB_DESCRIPTION>description de topic1</WEB_DESCRIPTION>
        </WEB>
    </WEB_LIST>
</MAIN>
