OUt of date
<?xml version="1.0"?>
<!DOCTYPE M [
<!ELEMENT I (T|(D?, C?, K))>
<!ELEMENT T (#PCDATA)>
<!ELEMENT D (#PCDATA)>
<!ELEMENT C (#PCDATA)>
<!ELEMENT K (#PCDATA)>
<!ELEMENT S EMPTY>
<!ELEMENT M ((T|(D?, C?, K)), (I|M), (S?, (I|M))*)>
]>
<M>
<K>MY MENU KEY</K>
<I>
<K>MY KEY</K>
</I>
<S/>
<I>
<K>MY KEY 1</K>
</I>
</M>
